### ISSUE TITLE
Fix: Tabla periodica HTML

### ISSUE THREAD

**Issue by LucianoRicardo737** [ManzDev/backlog#16]
Hola, estaba revisando tu curso de html y me parecio genial la tabla periodica. Pero es muy incomodo no podes seleccionar una categoria y que los elementos destacados queden fijos. Podrias arreglar eso porfa?

**Comment by ManzDev** [comment]
Hola @LucianoRicardo737,

¡Gracias por el comentario! ¡Hecho!
https://lenguajehtml.com/html/introduccion/tabla-periodica-html5/
